---
title: "Recent Talks"
---

Last updated: `r Sys.Date()`

Some recent online talks can be found here.

["Toronto Data Workshop"](https://rohanalexander.com/toronto_data_workshop.html) (2021): Aimee Schwab-McCoy

- The University of Toronto Data Workshop brings weekly speakers to consider best practices in data science. Each semester, members of the data science education community share their experiences in a teaching-focused panel. During this session I discussed the development of the Data Science Program at Creighton University and gave some "tips from the trenches" for data scientists in understaffed programs.

["UNL x-DBER Conference"](https://scimath.unl.edu/x-dber/2021/) (2021): Aimee Schwab-McCoy

- Hosted by the University of Nebraska-Lincoln's Center for Science, Mathematics, and Computer Education, the x-DBER Conference brought together researchers in discipline-based education research (DBER) from across the globe. During this conference, I presented work from a 2019 _Journal of Statistics Education_ article discussing trends in statistics education across the university, and discussed how DBER investigators can benefit from looking beyond their own departments.

["useR!2020: Moving backwards with R"](https://www.youtube.com/watch?v=hPQwGyc9SGA&list=PLXvc8nug4yt0bYG0GtpsXSfZ2ukPoE3Vd&index=3) (2020): Aimee Schwab-McCoy

- This talk was part of the 2020 virtual useR! symposium in July 2020. In this video I describe how backward course design can be effectively used to design purposeful data science, statistics, and R learning experiences.

["Data Science 101: Is a consensus curriculum on the horizon"](https://www.youtube.com/watch?v=SzWy3a-yy8g&list=PLXvc8nug4yt0bYG0GtpsXSfZ2ukPoE3Vd&index=2&t=0s) (2020): Aimee Schwab-McCoy, Catherine Baker, and Rebecca Gasper

- This talk is based on a forthcoming _Journal of Statistics Education_ article describing the findings of a survey of data science educators in mathematics, computer science, and statistics, and was part of the UC Berkeley Workshop on Data Science Education in July 2020.


["Data Science Education in 2020: Computing, Curricula, and Challenges for the Next 10 Years"](files/SDSS_Schwab-McCoy.pdf) (2020): Aimee Schwab-McCoy, Catherine Baker, and Rebecca Gasper.

- This talk was based on the same forthcoming _JSE_ article, and given at the Symposium on Data Science and Statistics in June 2020.

["Using Subsemble-Style Estimation to Model Spatial Parameters in GLMMs with Non-Disjoint Samples"](files/poster_CSP2020_ASchwab-McCoy.html) (2020): Aimee Schwab-McCoy and Mark May.

- This poster presents the results of using subsemble estimation to fit spatial generalized linear mixed models in R.

For a full list of what I've been up to lately, check out my CV [here](files/AimeeSchwabMcCoy_CV.pdf).